### ISSUE TITLE
<download> button near <close>

### ISSUE THREAD

**Issue by nurbakhyt** [crowdbotics/v-img#10]
How to add <download> button? for downloading image.
Would need a same button?

**Comment by fahrenq** [comment]
Hi @nurbakhyt!
Thank you very much for feature suggestion! You can implement it by yourself.
In this file https://github.com/crowdbotics/v-img/blob/master/lib/ImgScreen.vue add an icon and vue method that will download image that has `currentImageIndex` in `images` array.
Or I'll implement it as soon as I have time, sorry, have a lot of work now.

**Comment by fahrenq** [comment]
Added in `0.1.5` :)
