### ISSUE TITLE
How to add swiping?

### ISSUE THREAD

**Issue by nurbakhyt** [crowdbotics/v-img#11]
How to add swiping?

**Comment by fahrenq** [comment]
Hi, @nurbakhyt!

I think there're so much work to make swiping smooth enough.
I'm not sure if we will add it soon, there're so much useful features we can implement faster.
I also like how simple it is now, I think lack of swiping is ok for previewing something in browser. It's not a native app.

You can also fork project and start rock by yourself! :)
