### ISSUE TITLE
TypeError: screen is not a constructor

### ISSUE THREAD

**Issue by yk5tc** [crowdbotics/v-img#12]
no screen method？why？

**Comment by fahrenq** [comment]
Hey! Thanks for creating issue. Can you please provide some more details?

**Comment by yk5tc** [comment]
how to show different large pictures with another size?
like this:
<img v-img="{ group: xxxx, lsrc: large.png}"  lsrc="large.png" src="small.png">
?

**Comment by yk5tc** [comment]
<img v-img="{ group:xxx, lsrc: large.png" lsrc=" large.png" src="small.png">

**Comment by yk5tc** [comment]
`<img v-img="{ group:xxx, lsrc: large.png" lsrc=" large.png" src="small.png">?`

**Comment by yk5tc** [comment]
how to show different large pictures with another size?
like this:`<img v-img="{ group:xxx, lsrc: large.png" lsrc=" large.png" src="small.png">` ?

**Comment by fahrenq** [comment]
I think it's referring #3.
I'll implementing it as soon as I have time or you can create PR if you have time :)
