### ISSUE TITLE
CDN link?

### ISSUE THREAD

**Issue by voroncv** [crowdbotics/v-img#15]
Do you have CDN link for globally install?

**Comment by fahrenq** [comment]
Hey, thanks for suggestion! There's no CDN yet, but I'll add it as soon as I have time.

**Comment by MartinKolarik** [comment]
You can use https://www.jsdelivr.com/package/npm/v-img

**Comment by fahrenq** [comment]
Adjusted plugin to use with CDN, added instructions to readme.
https://github.com/crowdbotics/v-img/commit/8c9e8e16cba91023b756d0e691b0096b771a5f8f
