### ISSUE TITLE
How to import

### ISSUE THREAD

**Issue by nick2il** [crowdbotics/v-img#16]
I know it's weird but I'm  trying to figure out how to import it to my project. Which file I need to import to my html template? Or should I use so module builder like webpack but I kinda confused with it what I should do 😕

**Comment by fahrenq** [comment]
Hello Nick!

Unfortunately now the only well-tested way is to install the plugin as npm package. You can find instructions how to do it in Readme.

**Comment by nick2il** [comment]
I installed it via yarn but I don't know what to do so it work. As I understood I need to use webpack and babel to make it work. But I have issues to configure it out.

**Comment by fahrenq** [comment]
Please, take a look at vue-cli https://github.com/vuejs/vue-cli

You can easily set up well-structured project that works out of the box with webpack.

**Comment by nick2il** [comment]
Ok thanks I try it out

**Comment by fahrenq** [comment]
Feel free to reopen issue if you'll have problems that I can help with.
Thanks.
