### ISSUE TITLE
Gallery keeps old image sources if they was changed dynamically.

### ISSUE THREAD

**Issue by voroncv** [crowdbotics/v-img#19]
When we dynamically change the image, the old image remains in the data-vue-img-src tag

**Comment by fahrenq** [comment]
Hey! Thanks for creating the Issue. There's another reference to this problem with addition examples: #18 

This bug will be fixed in next version.

Thanks!

**Comment by fahrenq** [comment]
Bug fixed in 0.1.2.

https://github.com/crowdbotics/v-img/commit/dc662bb31bc5aa4b66b6a6e7cd8bb7e440f67499#diff-6d186b954a58d5bb740f73d84fe39073
