### ISSUE TITLE
Different Image on Click / Srcset

### ISSUE THREAD

**Issue by mindbits** [crowdbotics/v-img#23]
It would be great if a different image on click could be set so a thumbnail could open a larger image. 

Or if Srcset would be supported for this?

**Comment by fahrenq** [comment]
Hello!

Thank you very much for feature suggestion.
we actually can add different image with src option like this:

```vue
<img v-img="{ src: 'src-to-display-in-gallery' }" src="thumbnail-src">
```

srcset support related to issue #3

I'll close issue if you don't mind. Feel free to reopen this or create new if you have any questions.

Thanks!
