### ISSUE TITLE
VueImg breaks SEO fetching.

### ISSUE THREAD

**Issue by kherona** [crowdbotics/v-img#24]
Hello, 

I have recently published a website and while I was trying to get goodle to crawl (fetch as Google) my page was returning blank. I started removing components one at a time to see what was going wrong until, the only fix was to remove Vue.use(VueImg), it seems somewhere along the lines you are changing some DOM attributes that upsets SEO bots.

You can test any vue project with VueImg on:
https://technicalseo.com/seo-tools/fetch-render/

Check any project that has vueImg in it, i.e:  https://v-img.review/
Then test the bots with other vuejs project. i.e: https://vuejs.mikesprague.me/shopping-cart/

I hope this can be a quick fix, otherwise I'll have to use other tool for images.

Thanks

**Comment by fahrenq** [comment]
Hello!

Thank you very very much for reporting the issue. It's very important!
Unfortunately, I've spend around 2 hours and couldn't fix this bug.
I empirically found out that lines:
```
const Screen = Vue.extend(ImgScreen);
vm = window.vueImg = new Screen().$mount('#imageScreen');
```

Don't affect the issue. At least directly.
Will try to fix it asap.

Thanks.

**Comment by fahrenq** [comment]
Can't imagine I found this. @kherona, please, if you have time, can you update to the version 0.1.4 and test it one more time on your site?
At least it works with https://v-img.review/
Thank you very very much for reporting this bug.
