### ISSUE TITLE
Show different images on click

### ISSUE THREAD

**Issue by ch1c0t** [crowdbotics/v-img#25]
Thank you for this awesome plugin. Very convenient.

If time permits, could you please suggest an easy way to show different images inside the lightbox?

I have two sets of images([big](https://github.com/ch1c0t/e3d.site/tree/master/src/components/Portfolio/images/big) and [small](https://github.com/ch1c0t/e3d.site/tree/master/src/components/Portfolio/images/small)). When a user clicks on a small image, the corresponding big image should appear in the lightbox.

**Comment by fahrenq** [comment]
Hello!

I've answered for similar question in #23.

Unfortunately there's no way yet to preload big image, so, when user opens gallery he should wait  until browser will load the big image. We should at least add loader, but I don't have time for it yet.

**Comment by ch1c0t** [comment]
>Unfortunately there's no way yet to preload big image, so, when user opens gallery he should wait until browser will load the big image.

Thanks. That's good enough for me at the moment.
