### ISSUE TITLE
How to pass dynamic group in v-for.

### ISSUE THREAD

**Issue by Veado** [crowdbotics/v-img#30]
I need render a list dynamically.
eg:
```
<ul>
    <li v-for="(item, index) in list" :key="item.id">
        <a  v-text="item.title"></a> 
        <div class="images">
            <img v-img:index v-for="img in item.img" :src="img">
        </div>
    </li>
</ul>
```
This plugin working good!But i can't pass dynamic argument to custom directives, how to pass the argument?

**Comment by fahrenq** [comment]
Hello!
You just need to add group option like this:
```vue
<img v-img="{ group: index }" src="...">
```
Thanks!
Feel free to reopen the issue or create new one  in case I can help you with something else.
