### ISSUE TITLE
Open image on doubleclick

### ISSUE THREAD

**Issue by akubasa** [crowdbotics/v-img#33]
We need to only show the v-img on double click.
As of now it seems not to be possible

**Comment by fahrenq** [comment]
Thank you very much for feature suggestion.

**Comment by fahrenq** [comment]
Hey!
Implemented in 0.1.6 https://github.com/crowdbotics/v-img/commit/5f81958bc1aca67e0b31da4ee6b365952d39d964

Usage:
```vuejs
<img v-img="{ openOn: 'dblclick' }" src="...">
```
