### ISSUE TITLE
Error in directive img update hook: "TypeError: Cannot read property 'src' of undefined"

### ISSUE THREAD

**Issue by akubasa** [crowdbotics/v-img#36]
```vue
<img v-img= " { src: 'anySrc' } ">
```

If `<img>` does not contain a src="" following error will be printed on every click. 

_Error in directive img update hook: "TypeError: Cannot read property 'src' of undefined"_

**Comment by fahrenq** [comment]
Hello!

I'm sorry but what behavior do you expect in this case? Which image should be shown at non-opened <img>?

**Comment by akubasa** [comment]
v-img is working correct, but it will print the error: "Error in directive img update hook: "TypeError: Cannot read property 'src' of undefined" in the console on every click.

**Comment by fahrenq** [comment]
Hey!
Thank you very very much @akubasa for this bug report! It was pretty critical bug that blocked dynamic options from update if `<img>` has no attributes.
Fixed in 0.1.9 https://github.com/crowdbotics/v-img/commit/97c8e8fd01c116d339a7ee3ea456e0e2d5c0bf54

Thank you very much for help!
