### ISSUE TITLE
Some suggests for v-img~

### ISSUE THREAD

**Issue by dragon-yuan** [crowdbotics/v-img#37]
Dear Develpoer：
Thank you very much for developing this 'v-img'.Easy to use it.
I hope you can add the zoom and flip function of the picture.
Encountered in the work, but can not be resolved, I hope developers can provide, thank you very much~
User, Dragon.  o(∩_∩)o

**Comment by dragon-yuan** [comment]
Maybe a small bug.
When images path is acquired asynchronously (AJAX) ，The number of images shown above is not from 1.
For example, I have 3 pics, but the 'span' show '3/3' , not start with '1/3'.
Hope the writer will check in his busy schedule. Thanks~

**Comment by fahrenq** [comment]
Hello!

First of all, many thanks to you for all suggestions!

1. Zoom and flip functionality. I think we can add zoom functionality relatively easy with current code structure. However, I'm not sure in 'flip'. What do you mean? Animation of swiping left/right or?
2. Can you please provide a bit more details about the bug you experienced? It would be good to see a piece of code if it's possible. 

Thank you very very much for feature suggestions and bug reports! Unfortunately, I'm very busy these days, can't tell you how soon features will be implemented. Will try to fix bugs as soon as I can clearly reproduce it.
Thanks!

**Comment by dragon-yuan** [comment]
Thanks dear fahrenq~~~
The picture flips like this picURL: http://net.dragon-yuan.me/images/github-img/20171122164816.png
I am a front-end rookie, thank you very much for replying to this issues in your busy schedule. Thank you! Heart!
