### ISSUE TITLE
Caption on gallery screen

### ISSUE THREAD

**Issue by AhmedAtef07** [crowdbotics/v-img#4]
Would like to see the ability to add caption to the image

**Comment by fahrenq** [comment]
Great suggestion, @AhmedAtef07.
It's on the way!
Thanks.

**Comment by fahrenq** [comment]
Implemented in 0.0.9
https://github.com/crowdbotics/v-img/commit/8a004a9b75b0c9263f3bc9e35ac70e506e920da9
Thank you!
