### ISSUE TITLE
Can I use this on ssr?

### ISSUE THREAD

**Issue by k1ll1n** [crowdbotics/v-img#43]
I get an error
`[Vue warn]: Failed to resolve directive: img`

my code

```
<template>
  <div>
    <img v-img="{ title: 'art' }" src="https://www.walldevil.com/wallpapers/a43/anime-artistic-widescreen-wallpapers-wallpaper.jpg" width="200px"/>
  </div>
</template>

<script>
import VueImg from 'v-img'

export default {
  name: "my-gallery",
  components: {VueImg}
}
</script>
```

**Comment by fahrenq** [comment]
Hi @k1ll1n.

Yes, you can use v-img with ssr (I tested it with Nuxt.js, but don't think it won't work with hand-written ssr).

We don't have to register `v-img` as a component. Instead, you need to 

```javascript
import vImg from 'v-img';
Vue.use(vImg);
```
Please, take a look at README for more information.

If you're using nuxt.js - you'll need to use 'plugins' feature - https://nuxtjs.org/guide/plugins/#vue-plugins

Thank you. Feel free to reopen this issue or open a new one if you'll have any other questions.

**Comment by k1ll1n** [comment]
@fahrenq Thank you!
It helped me!
