### ISSUE TITLE
Possible to add img thumbnail source?

### ISSUE THREAD

**Issue by jstnjs** [crowdbotics/v-img#48]
Right now I have:
`<img v-img="{title:'Lorem', group:'gallery', thumbnails: true, src: 'http://placehold.it/800x800" src="http://placehold.it/400x400">`

This is great, but I would prefer to have three image sizes.
1. Original img size
2. Thumbnail img size
3. Pop up img size

Am I missing something and is this already possible or?
Would appreciate it if you can add the thumbnail size :)

**Comment by fahrenq** [comment]
Hi @Justintijd!

Unfortunately, it's not possible yet.

I don't think we should explicitly add an attribute for thumbnail size. It's better to implement srcSet support as #3 suggests.

Sorry, don't have time to work on the plugin now, but thank you very much for the suggestion!

I'll notify you in this issue once the feature will be supported.

Thanks.
