### ISSUE TITLE
transition typos

### ISSUE THREAD

**Issue by jkiimm** [crowdbotics/v-img#5]
There are typos at a transition name attribute. [one](https://github.com/crowdbotics/v-img/blob/498896b560f255ab4ad2457e53eb61ed6e0659d2/lib/ImgScreen.vue#L32), [two](https://github.com/crowdbotics/v-img/blob/498896b560f255ab4ad2457e53eb61ed6e0659d2/lib/ImgScreen.vue#L43)

I guess it should be `v-img-fade` and I can't see transition about `img-fade` now.

**Comment by fahrenq** [comment]
Thank you very much @jkiimm for the report!
I've fixed first one and deleted second, since it wasn't necessary.
Appreciate your attentiveness!
