### ISSUE TITLE
Close the gallery programmatically

### ISSUE THREAD

**Issue by diancabral** [crowdbotics/v-img#51]
Hi!

I'm building a mobile application and I used the plugin to create image viewer. When I click on back button of android, the vue-router back to previous page but the gallery overlay continue showing.

How to close the gallery programmatically? With this resource i can use the "beforeRouterLeave" to run a method than close the gallery.

**Comment by fahrenq** [comment]
Hi! Related to #21.

Actually, there's no way to do it now, sorry. I'm planning to continue developing the plugin and this feature has almost the highest priority.

If you need it urgently - I'd advise store Vue instance created in plugin in some global main Vue instance variable and simply emit some events to close the instance

**Comment by tartinesKiller** [comment]
Hey there, I've found another hack, maybe more convenient to apply.
v-img closes the fullscreen when the Escape key is pressed: https://github.com/crowdbotics/v-img/blob/c74dc0d8bafadbc5246bb0bc77a1a6c3d7f5d7dc/lib/ImgScreen.vue#L155
So you can programmatically fire an escape key press, thanks to:
`window.dispatchEvent(new KeyboardEvent("keyup", {keyCode: 27}));`

It's the cleanest option I've found for now, I hope it'll work for you! (and hope it's not too late)
