### ISSUE TITLE
How to make image responsive and define the sizes?

### ISSUE THREAD

**Issue by harishankards** [crowdbotics/v-img#52]
```html
<img v-img v-for="file in this.awardData.files" :key="file.id" :src="'http://localhost:3000/'+file" />
```

The above is my code. When I embed into the component, it's displaying the full size of the image. How do I prevent it?

**Comment by harishankards** [comment]
@fahrenq just wanted to check whether do I have got any updates or not.

Looking forward

**Comment by fahrenq** [comment]
Hey.
I'm sorry, not sure I understand the question.

**Comment by harishankards** [comment]
@fahrenq, When I use the above line of code to display the images, I could not make it fit into the frame. Rather it takes up its original size and spoils the page.

Now, I want to keep it fit the place wherever I put. Is this doable via your package?

**Comment by fahrenq** [comment]
Sorry, still can't understand you...

You mean, `<img>` object doesn't fit its container? If yes - you can apply styles to this `<img>` tag as regular with CSS.

If you want full-page preview to fit some container - I think its impossible with the package.

**Comment by harishankards** [comment]
Okay @fahrenq
