### ISSUE TITLE
vue/no-unused-components incorrectly reporting

### ISSUE THREAD

**Issue by half2me** [crowdbotics/v-img#58]
I use the following component: https://github.com/crowdbotics/v-img

I have this:
```html
<template>
  <img v-img src="">
</template>
```
```javascript
import VueImg from 'v-img';
...
components: {
  ...
  VueImg,
},
```

When I run `eslint` I get the following error:
`error  The "VueImg" component has been registered but not used  vue/no-unused-components`

I'm guessing this is probably because the component is not instantiated directly, but rather just attached to the `<img>` tag.

**Comment by fahrenq** [comment]
Hi,

You don’t need to register component, only Vue.use

Thanks

**Comment by half2me** [comment]
@fahrenq sorry if its just my misunderstanding, but isn't `Vue.use` for registering components globally? I only wish to use v-img on a single component, not globally.

https://stackoverflow.com/questions/48066237/how-to-use-a-vue-js-plugin-inside-a-custom-component

**Comment by fahrenq** [comment]
v-img is not a component but a directive. Sorry but I didn't ever thought
of registering it for only one component.
Now module only exports object that can be used with Vue.use()

**Comment by half2me** [comment]
Oh, my bad :') I only just realized I submitted the issue to v-img instead of https://github.com/vuejs/eslint-plugin-vue . Its been a long day :)

**Comment by half2me** [comment]
I've reported the issue here: https://github.com/vuejs/eslint-plugin-vue/issues/571
