### ISSUE TITLE
Group dynamically inside v-for

### ISSUE THREAD

**Issue by Reda-bx** [crowdbotics/v-img#6]
Hi, I have a v-for iterating over `items` array its looks like this
```
<div v-for="item in items" class="card-container">
  <div class="card-image">
    <div class="main-image">
      <div v-for="thumbnail in item.thumbnails">
        <img v-img :src="thumbnail" alt="">
      </div>
    </div>
  </div>
</div>
```
How can I group each item so I can get diffrent slideshow? is this event possible?

**Comment by fahrenq** [comment]
Hi, @Reda-bx! Very good question! I think it's not possible right now, but I can see this functionality in @zili2000 fork.

@zili2000, can you please create PR once it's convenient to you? :)

**Comment by Reda-bx** [comment]
hi @fahrenq what about something like `v-img="{group: your_value}"`? 
(I can PR, I implemented already)

**Comment by Reda-bx** [comment]
Oh never mind, @zili2000 did it, when you have a moment, please PR

**Comment by fahrenq** [comment]
You can use it now from your package, I'll notify once we update :)

**Comment by fahrenq** [comment]
I'm so sorry, @zili2000, it's been 2 weeks. Added this functionality:
https://github.com/crowdbotics/v-img/commit/4fb1220d2855483e512c99960166f666872c2ece

**Comment by Reda-bx** [comment]
hi @fahrenq, in this [line](https://github.com/crowdbotics/v-img/blob/master/lib/index.js#L50) can you add double quotes so it will be something like this `img[data-vue-img-group="${group}]"` , its throwing an error

**Comment by fahrenq** [comment]
Hi, @Reda-bx! Done! Thank you very much!

Can you please tell me, which browser do you use? It was ok in chrome btw.

**Comment by Reda-bx** [comment]
@fahrenq chrome

**Comment by Reda-bx** [comment]
Hi @fahrenq any updates?

**Comment by fahrenq** [comment]
Hi, @Reda-bx.
I added quotes 5 days ago in version 0.0.8, you can test it!
Lmk if any errors!

**Comment by Reda-bx** [comment]
@fahrenq 🎉
