### ISSUE TITLE
Not working changed(imageIndex)

### ISSUE THREAD

**Issue by sawsam** [crowdbotics/v-img#63]
Not working changed(imageIndex)

**Comment by rafaelmagalhaes** [comment]
for me changed event is running when page is loading, i console logged the index and I can see the index when page is loaded,
this is on a v-for

`   <img  v-img="{src:image.downloadUrl,thumbnails:true,openOn: 'click',group:'gallery', changed:changeImage(index)}" v-for="(image,index) in gallery" height="300px"  :key="index" :src="image.dataUrl" alt="">`

**Comment by sawsam** [comment]
The problem has been solved. Thank you for your reply.

**Comment by rafaelmagalhaes** [comment]
can you give me an example because i cant get it work ?

**Comment by sawsam** [comment]
You try it.
<img v-img="{src:image.downloadUrl,thumbnails:true,openOn: 'click',group:'gallery', changed:changeImage}" v-for="(image,index) in gallery" height="300px" :key="index" :src="image.dataUrl" alt="">

**Comment by sawsam** [comment]
changed:changeImage(index)  change to changed:changeImage.

**Comment by rafaelmagalhaes** [comment]
that works

but if you have thumbnails set to true it doesn't trigger the function, also how do you pass properties to the function as soon I put anything I get the same problem returns everything on page load

**Comment by sawsam** [comment]
Thumbnails do not trigger functions

**Comment by sawsam** [comment]
what do you mean ‘’ returns everything on page load‘’

**Comment by rafaelmagalhaes** [comment]
if I pass the image property  on changeImage(image) it doesn't work just returns all the objects when the page is rendered

**Comment by sawsam** [comment]
No need to pass parameters
`v-img="{group: 'group', changed: onIndexChanged}"`
