### ISSUE TITLE
*.mjs webpack error

### ISSUE THREAD

**Issue by BrunnerLivio** [crowdbotics/v-img#7]
Hey there!

When I tried to use v-img using webpack, it said it does not know the extension `.mjs`. Thats because the package.json points to `dist/v-img.mjs`. Is that a typo, or should it really be `*.mjs`? If so, may I ask why?

**Comment by fahrenq** [comment]
Hi @BrunnerLivio!

Did you include package with `require()` but not with es6 `import`?

**Comment by BrunnerLivio** [comment]
I used es6 import

```
import VueImg from 'v-img';
Vue.use(VueImg);
```

**Comment by fahrenq** [comment]
Hm, it's very strange!

I've just tested it and it works good for me!

I'm so sorry, don't know how to reproduce your error.
Can you please fork the library, change `*.mjs` to `*.js` and install library from your github?
You can find how to install npm packages from github here: https://docs.npmjs.com/cli/install

You'll help a lot if tell that this will fix your issue.

**Comment by fahrenq** [comment]
@BrunnerLivio gotta get mjs back because setting 'module' to '.js' will add some nodejs stuff to the browser-file when building. Probably your setup was wrong that you got this error. Hope everything will be ok in future.

**Comment by mayank-shaan** [comment]
import VueImg from 'v-img/dist/v-img';

Try importing the file like this to resolve the path
