### ISSUE TITLE
when i view on my popup Components,the z-index was less than popup，then can not display

### ISSUE THREAD

**Issue by jjjachyty** [crowdbotics/v-img#9]
i want modify the .fullscreen-v-img css ，but take effect

**Comment by fahrenq** [comment]
Hi, @jjjachyty!
I'm so sorry for a late response. I'm not sure, but maybe you can override the needed properties with `!important` css flag?

**Comment by fahrenq** [comment]
Fixed in last update. Thanks for the report!
https://github.com/crowdbotics/v-img/commit/8a004a9b75b0c9263f3bc9e35ac70e506e920da9#diff-24b81baa0f7609331b1c77658802a2f2R140
